apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cart-pvc
spec:
  storageClassName: vsan-default-storage-policy
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  # Updated with proper port names for ArgoCD validation
spec:
  selector:
    app: cart-service
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
      annotations:
        kubernetes.io/change-cause: "Fixed cart clearing after purchase, updated success message"
        date: "2024-01-$(date +%d)"
        timestamp: "$(date +%s)"
    spec:
      containers:
      - name: cart-service
        image: ghcr.io/niranec77/example-music-store-1-cart:1.0.36
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: STORE_SERVICE_URL
          value: "http://music-store-1-service:5000"
        - name: ORDER_SERVICE_URL
          value: "http://order-service:5001"
        - name: CART_DB_PATH
          value: "/app/data/cart.db"
        volumeMounts:
        - name: cart-data
          mountPath: /app/data
      volumes:
      - name: cart-data
        persistentVolumeClaim:
          claimName: cart-pvc 