apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-store-1-pvc
spec:
  storageClassName: vsan-default-storage-policy
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-store-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-store-1
  template:
    metadata:
      labels:
        app: music-store-1
    spec:
      containers:
      - name: music-store-1
        image: ghcr.io/niranec77/exmaple-music-store-1:latest # Change to your image repo if pushing to a registry
        ports:
        - containerPort: 5000
        env:
        - name: DB_PATH
          value: /data/music_store.db
        volumeMounts:
        - name: music-store-1-data
          mountPath: /data
      volumes:
      - name: music-store-1-data
        persistentVolumeClaim:
          claimName: music-store-1-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: music-store-1-service
spec:
  type: LoadBalancer
  selector:
    app: music-store-1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007 