apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-pvc
spec:
  storageClassName: vsan-default-storage-policy
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  # Updated with proper port names for ArgoCD validation
spec:
  selector:
    app: order-service
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        kubernetes.io/change-cause: "Updated styling - brighter background"
    spec:
      containers:
      - name: order-service
        image: ghcr.io/niranec77/example-music-store-1-order:1.0.22
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: STORE_SERVICE_URL
          value: "http://music-store-1-service:5000"
        - name: ORDER_DB_PATH
          value: "/app/data/orders.db"
        volumeMounts:
        - name: order-data
          mountPath: /app/data
      volumes:
      - name: order-data
        persistentVolumeClaim:
          claimName: order-pvc 