apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-store-1-pvc
spec:
  storageClassName: vsan-default-storage-policy
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-store-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-store-1
  template:
    metadata:
      labels:
        app: music-store-1
      annotations:
        kubernetes.io/change-cause: "Updated styling - removed animations, brighter background"
    spec:
      containers:
      - name: music-store-1
        image: ghcr.io/niranec77/example-music-store-1-store:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: CART_SERVICE_URL
          value: "http://cart-service:5002"
        - name: ORDER_SERVICE_URL
          value: "http://order-service:5001"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "music_store"
        - name: DB_USER
          value: "music_user"
        - name: DB_PASSWORD
          value: "music_password"
        # Static files are included in the Docker image, no volume mount needed
---
apiVersion: v1
kind: Service
metadata:
  name: music-store-1-service
  # Updated with proper port names for ArgoCD validation
spec:
  type: LoadBalancer
  selector:
    app: music-store-1
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007 