version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: music_store
      POSTGRES_USER: music_user
      POSTGRES_PASSWORD: music_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U music_user -d music_store"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 