name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug repository info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Repository owner: ${{ github.repository_owner }}"
          echo "Repository name: ${{ github.event.repository.name }}"
          echo "Event repository: ${{ github.event.repository.full_name }}"

      - name: Set image name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "Final image name: ghcr.io/${{ github.repository_owner }}/$REPO_NAME:${{ github.event.inputs.image_tag }}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ github.event.inputs.image_tag }}

      - name: Success message
        run: echo "Successfully built and pushed ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ github.event.inputs.image_tag }}" 